### ISSUE TITLE
Looking at 3rd algorithm for Morphing

### ISSUE THREAD

**Issue by dalisoft** [dalisoft/Unim.js#2]
Hi @timo22345, @Emasoft, @uddipan, @alexk111.
Credits goes you're if we make this with sharing code together
I looking for `SVG 3rd Morphing algorithm`, but i can't make it work.
I have 2 algorithm.

1-st: `path2curve`
Faster actually, but can't change `morphIndex`

2-st: `D3 algorithm, getPointAtLength`
Slower, but more best looking (`morphIndex`)
Have some limitation for shape morphing

Or maybe we combine of both for better performance and best looking

**Comment by Emasoft** [comment]
@dalisoft Thank you dalisoft. I'm currently studying the Uddipan morpher tool source code (not public, a courtesy of Uddipan to me), to port the algorithm in javascript and apply it to SVG. It is very complex, especially the math, and I'm still far from having grasped it. But if I reach some initial result I will get back to you. 

Those are the references:

Shape Morphing Algorithm by
Uddipan Mukherjee
University of California, Irvine, CA
email:  umukherj@ics.uci.edu

Paper:
http://www.ics.uci.edu/~gopi/SamplePubs/Tweening.pdf

Morphing of self-overlapping curves - video: 
http://youtu.be/EHBdTD5EA6M
http://youtu.be/0DDC3fbwtIw

**Comment by Emasoft** [comment]
I also suggest you to contact @thednp . His algorithm for morphing (used in his Kute library, https://github.com/thednp/kute.js  ) is not as good as the GSAP SVG Morpher, and I think he will be as interested as us in developing a better one.

**Comment by thednp** [comment]
@Emasoft the current SVG Morph from KUTE.js is inspired by the D3.js examples, it's not the best for performance or visual, but it's the lightest. Me and @dalisoft worked/tested on a better plugin and I have decided to go this way, he decided to do them all, so aside from GSAP, now you have alot more options.

**Comment by Emasoft** [comment]
@thednp Thanks, but I'm not satisfied with the current methods. Both path2curve and D3 method are not smooth enough, and neither is the GSAP one. Overlapping still happens, both with a single path shape and with a group of shapes. It is also not able to handle complex shapes morphing without producing artifacts, or merge multiple shapes into one. We are a long way from a robust realtime morphing algorithm you can throw just anything at. We need to research more. I'm working on this, and I'm also working on an SVG SMIL animation exporter for OpenToonz. Generating in between frames is the holy grail here. Currently no one can beat the animation software "CACANi" in this area. And that is my reference when I evaluate vector morphing algorithms.
Look at what CACANi can do when morphing between only 2 key frames: 
https://www.youtube.com/watch?v=g8z1YDfIG2w
https://www.youtube.com/watch?v=5U1k_psU4o8

**Comment by thednp** [comment]
@Emasoft there is no way to code something to do multi-path/group paths morph out of the box. There is no such thing. If you would read my page with examples on the [KUTE.js SVG Plugin](http://thednp.github.io/kute.js/svg.html), you will understand.

**Comment by dalisoft** [comment]
@thednp Thanks for replies. My js does group morphing, not best, but enough, made by @alexk111.
@Emasoft If you have script working with fast-performance, please share it with we, and we convert it to Javascript, maybe we improve. Of course, i readed this book more than 100-times, and watched videos. Maybe you can give we algorithm of `Cubic bezier >> Control points >> Smoothing`.

Thanks

**Comment by dalisoft** [comment]
@Emasoft i see your comment everywhere where have `morph` stuff. Maybe you interested in this? Or you trying to make one morphing with combine all things? Thanks

**Comment by thednp** [comment]
@dalisoft I think there is no other way to code SVG Morphing, so you can close this issue.

**Comment by dalisoft** [comment]
@thednp maybe will be, i hope we find best way

**Comment by dalisoft** [comment]
@Emasoft What about triangulation ("delaunay"), i have demo and it works. but it's not a "Cubic / Smooth" an just like Line-To-Line and have corners, not smooth as original shape

**Comment by dalisoft** [comment]
As i trying to develop 3rd algorithm, i have 3rd algorithm and upload as soon as possible.
<b>I Close Issue as <i>SOLVED</i></b>
